### ISSUE TITLE
Play/Run a DICOm .dcm files using cornerstoneWADOImageLoader

### ISSUE THREAD

**Issue by MayurSahu** [chafey/cornerstoneWADOImageLoader#24]
Hello chafey,
                 How can we play/run a .dcm file in browser using cornerstoneWADOImageLoader ?.I've used your code to display the dcm file in my web application now i was wondering if it could get played as well.

**Comment by swederik** [comment]
Hi Mayur,

You're looking for Cornerstone Tools (https://github.com/chafey/cornerstoneTools). There is a tool called playClip that can be used for this.

There is a helpful example here:
https://rawgit.com/chafey/cornerstoneTools/master/examples/stackScroll/index.html

Just use your browser's "view-source" button to check how it's done.

If you have any further questions, they would be best directed to the Cornerstone google group:
https://groups.google.com/forum/#!forum/cornerstone-platform

I'll close this issue now because it's unrelated to the WADO Image Loader.
