### ISSUE TITLE
Error on Loading Local file via wadouri:localpath

### ISSUE THREAD

**Issue by pujasanjay** [chafey/cornerstoneWADOImageLoader#62]
Sir
Tool : cornerstoneWADOImageLoader-master
Method : wadouri

On pasing the parameter : a/1.3.46.670589.11.8362.5.0.2672.2014092515570109004.dcm
this is a file on the local system. A error is raised in with alert message object xmlHttpRequest.

Kindly help

Regards

Dr Sanjay Gupta

**Comment by chafey** [comment]
wadouri only loads files over http, you can't load a local file that way.  The web browser security mechanism won't let you load local files without user interaction

**Comment by pujasanjay** [comment]
Sir
Is there a way to load the local files. 

How can dicom file information be converted to base64 data.

Regards

Dr Sanjay Gupta

**Comment by swederik** [comment]
Please see the DICOM File example for loading local files:

https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

I don't know why you want to convert to base64, but it is not necessary for viewing the images. The examples in Cornerstone are only encoded in base64 so that we can have self contained examples.

Hope that helps!
