### ISSUE TITLE
MRI Images showing up as black

### ISSUE THREAD

**Issue by mikewolfd** [chafey/cornerstoneWADOImageLoader#73]
Hello,

I'm attempting to view an MRI study that displays fine in Osirix and is parsable by dicomParser. Using cornerstone it shows up as a black image.

Initially I thought it was cornerstone, but I've come to think it's the WADOImageLoader. I tried reading it as an uncompressed image with the same issue so I don't think it's a codec issue.

I'm honestly at a loss. I've included an anonymized example.

[IM-0001-0005.dcm.gz](https://github.com/chafey/cornerstoneWADOImageLoader/files/878017/IM-0001-0005.dcm.gz)

**Comment by swederik** [comment]
Hi Mike,

Yes this is a weird one. Thanks for the report!

**Comment by mikewolfd** [comment]
I figured out the surface problem, and a temporary work around, but not how to fix it. 

It seems that the DICOM's minPixelValue and maxPixelValue aren't correct. I mean the difference are correct, but the PixelData has a normalization offset of 32768. If I force the getMinMax function to run, the image displays fine.

**Comment by jpambrun** [comment]
```
(0028,0106) US 0                                        #   2, 1 SmallestImagePixelValue                                                                                                  
(0028,0107) US 4334                                     #   2, 1 LargestImagePixelValue                                                                                                   
(0028,1050) DS [34935]                                  #   6, 1 WindowCenter                                                                                                             
(0028,1051) DS [4334]                                   #   4, 1 WindowWidth  
```
that's odd.

**Comment by jpambrun** [comment]
I was under the impression that we always check min/max ourselves as DICOM headers can't really be trusted. Also, if the min/max values are slightly incorrect (say just by one) it may appear correctly, but the lut will not cover the entire range and this will result in severe performance regression.

**Comment by swederik** [comment]
It does not look like that is the case:

https://github.com/chafey/cornerstoneWADOImageLoader/blob/bb70db9fb39f09932255bf93e2fcd46d6a9467b4/src/imageLoader/createImage.js#L113
https://github.com/chafey/cornerstoneWADOImageLoader/blob/73ed7c4bbbd275bb0f7f9f363ef82575c17bb5f1/src/webWorker/decodeTask/decodeTask.js#L47

It seems we only calculate it if it isn't provided.

**Comment by chafey** [comment]
We used to always calculate it because bad things happen if the DICOM
values are wrong.  Unfortunately doing "automatic" corrections like this
does not expose the underlying issues in the data and thus the issue is
propagated.  I therefore want cornerstone to first and foremost be
standards compliant and provide hooks for developers to workaround bad data
like this.

**Comment by jpambrun** [comment]
I think we should use the true image array min/max when constructing the image lut, otherwise we will get 'undefined' out of it causing artefacts that can hard to see and performance degradation for the reminder of the browser session because of de-optimization.

For example, image with some pixel values slightly outside of the reported range will result in 'undefined' (```lut[-1]``` and ```lut[len(lut)+1]```  -> ```undefined```) that will be rendered as black once written to the canvas. Arithmetic computation with 'undefined' produces 'NaN' which (IIRC) is also displayed as black. This is hard to detect on the lower end of the lut (back in mostly black area), but immediately obvious at the other end (back pixels in white area). As a result, incorrect min/max can fail silently with de-optimization and hard to detect visual artefacts. 

Perhaps a console.warn would be a better signal for underlying file issues?
