### ISSUE TITLE
Color palette imagePixelModule metadata returns empty arrays

### ISSUE THREAD

**Issue by jpambrun** [chafey/cornerstoneWADOImageLoader#98]
It looks like something is wrong with the color palette metadata for the [attached image](https://github.com/chafey/cornerstoneWADOImageLoader/files/1047896/test.zip).

[blue|green|red]PaletteColorLookupTableData are all empty after [this point](https://github.com/chafey/cornerstoneWADOImageLoader/blob/75771408c961d8d0c2f3476b9b7f2d951bcd75f6/src/imageLoader/getImageFrame.js#L4).

**Comment by swederik** [comment]
![screen shot 2017-10-30 at 09 31 04](https://user-images.githubusercontent.com/607793/32161248-1f9b736c-bd55-11e7-97df-258658f0960c.png)

Thanks for the report! It turned out that the number of LUT entries in the LUT descriptor was being used as 0. In the DICOM standard it states "The first Palette Color Lookup Table Descriptor value is the number of entries in the lookup table. When the number of table entries is equal to 2ˆ16 then this value shall be 0.", so when it's 0 now we just use 65536 as the number of entires.
